tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/midwestern_state_university.py

Add Midwestern State University

---

tx_salaries/management/commands/import_salary_data.py

This is a revamp of the idea in #50 that's more in tune with what currently exists. The code #50 changed has changed under it significantly, so it'd be hard to reconcile it.
Allows for updates to happen.

Ask if an agency should be deleted if it already exists

---

tx_salaries/models.py

This query was trying to do way too much, bulking up the page load time on every page it touched.

Simplify get_top_level_departments query

---

tx_salaries/migrations/0017_auto__add_index_employee_compensation.py
tx_salaries/models.py

Crazy speed up from adding an index to this field. We do so much sorting on it.

Add index to employee.compensation field

---

setup.py
tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/austin.py

City of Austin is now added - would like to be made live!

Added City of Austin

---

dallas.py
tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/dallas.py

Woohoo!! Dallas wants to be represented in salaries!

Added city of Dallas

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/metropolitan_transit_authority.py

Metro Transit Authority yay transit!

added metro transit authority

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/texas_state_university.py

It works! Put on your party hat.

Texas state university

---

setup.py
tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/austin_isd.py

Austin isd

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/san_antonio.py

Let's add San Antonio to the db!

San Antonio

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/ut_dallas.py

This is an override to a previously existing UT Dallas transformer. 
One thing that might cause weirdness- it appears that employees are able to select multiple races and they appear as a list of races for each employee.

ut dallas transformer

---

ERRORS.md
README.rst
tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/ut_md_anderson.py

Making a separate pull request for this – I'd rather the README update pull be its own thing.

MD anderson

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/ut_medical_branch.py

Updated and appears to be working correctly

UT Medical Branch at Galveston

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/ut_health_northeast.py

This one is weird, and I'm putting it here so we don't forget about it until we decide what to do.
UT Health Northeast used to be called University of Texas Health Science Center at Tyler which we currently have in Salaries now.
Do we want to get rid of that one and plug in this new one, or are there weird things that could break?

Ut health northeast

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/texas_womans_university.py

Texas womans university

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/ut_health_houston.py

UT Health Houston transformer update for latest spreadsheet

---

tx_salaries/management/commands/import_salary_data.py
tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/texas_am_system.py

What it says on the tin.
Also adds support for removing multiple existing agencies from a single spreadsheet.

Update Texas A&M University System

---

tx_salaries/utils/transformers/texas_am_system.py

Forgot to account for the monthly rates. Fixes it.

Add custom descriptions and compensation rates for TAMU

---

tx_salaries/utils/transformers/ut_austin.py

Based on the few complaints we have received, I changed the wording.

changed annual salary to fiscal year allocation

---

ERRORS.md
tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/cypress_fairbanks_isd.py

Cy fair isd

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/ut_southwestern.py

Ut Southwestern

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/ut_tyler.py

Working UT Tyler Transformer

---

tx_salaries/management/commands/import_salary_data.py
tx_salaries/utils/transformers/base.py

@rdmurphy I'm trying to test it with your Tamu data but my computer isn't cooperating. This can be expected to create a merge conflict with my other modification to generic_merge_cell_transform when you eventually merge that into master.

Better behavior for invalid records.

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/dallas_isd.py

DALLAS ISD

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/tarrant_comm_college.py

Ready for testing and production!!!!!

Tarrantcomm

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/ut_permian_basin.py

Ut permbasin

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/college_station_isd.py

Data was pretty clean and easy to process. It ran fine for me!

Collegestationisd

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/ut_md_anderson.py

update md anderson

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/midwestern_state_university.py

Midwestern

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/tarrant_county.py

Tarrant county

---

setup.py
tx_salaries/utils/transformers/texas_am_system.py

DO IT DO IT! Data from 12/1/16, so its already kinda late, cuz temps and communication probs

texasam works hooooray

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/austin.py

city of austin updated

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/dallas.py

City of Dallas - update
YES
Check some temporary employees to make sure the rate is listed as hourly. For example, Bonnie Hill, listed as a job title of "Temporary Help" under the "Code Compliance Services," should have an hourly rate, not annual salary.

City of Dallas udpate

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/rockwall_isd.py

Rockwall ISD 
y
no it's perfect why would you even ask this.

Rockwall ISD

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/hays_county.py

Hays County (new)
Yes
http://raw.texastribune.org.s3.amazonaws.com/hays_county/salaries/2017-03/raw.xlsx
No, the data was super clean.

Add Hays county

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/williamson_county.py

Williamson County (new)
http://raw.texastribune.org.s3.amazonaws.com/williamson_county/salaries/2017-03/salaries.xlsx

Add Williamson County

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/metropolitan_transit_authority.py

Metropolitan Transit Authority
Yes
The descriptions are annoying but they work.

Metropolitan transit authority

---

tx_salaries/management/commands/import_salary_data.py
tx_salaries/utils/transformer.py
tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/state_of_texas.py

State of Texas Comptroller Payroll (Update)
Yup.
The curse of the NULL last name. Update needs to have `--skip-infer-types` passed to `import_salary_data` so it doesn't skip them.

Update State of Texas

---

README.rst
old/README.rst
tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/houston_isd.py
tx_salaries/utils/transformers/travis_county.py

Entity: Travis County
S3 URL: http://raw.texastribune.org.s3.amazonaws.com/salaries/2017-05/PIR.xlsx
Note: This pull request also includes the file for Houston ISD (which isn't quite ready) and updates to the readme file, which will need to be looked over. If you'd like me to split that into a different branch, let me know.

Add Travis County

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/ut_san_antonio.py

UT San Antonio, update
Yes
Nope

Update of UT San Antonio

---

tx_salaries/utils/transformers/ut_southwestern_mc.py

UT Southwestern MC - update
http://raw.texastribune.org.s3.amazonaws.com/ut_southwestern_medical/salaries/2017-05/12295_PIR_UTSW_Employees.xlsx
You had issues with blank rows when we he tried uploading this last, but I didn't have that issue. You fixed it by adding:
REJECT_ALL_IF_INVALID_RECORD_EXISTS = False
That's in the file now, just commented out.
Also, we were having issues with the last names showing up in front of first names. That's been resolved.

UT Southwestern MC

---

tx_salaries/management/commands/generate_transformer_hash.py
tx_salaries/management/commands/import_salary_data.py
tx_salaries/utils/transformers/tarrant_comm_college.py

Updates the deprecated `option_list` to the new `add_arguments()` method. 
https://docs.djangoproject.com/en/1.11/howto/custom-management-commands/#accepting-optional-arguments

Django update

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/dallas_county_comm_college.py

Dallas County Community College District - update
yes
no

Dallas county comm college

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/dallas_county.py

Dallas County - update
Yes
Nah

Dallas County

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/texas_tech_university_hsc.py

Texas Tech University Health Sciences Center - update
Yup
Nope

Texas Tech health sciences

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/ut_health_houston.py

UT Health Sciences Center Houston, update
ya
nope

Houston health sciences center

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/state_of_texas.py

state of texas, update obvs
ya
The Null family. Run update with `--skip-infer-types` to avoid problems.

Comptroller

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/tarrant_county.py

Tarrant County - update
Yep
Nope

Update Tarrant County

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/ut_arlington.py

Update UT Arlington

---

tx_salaries/utils/transformers/state_of_texas.py

State of Texas (update)
Yes
No

Merge state of Texas employees together

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/ut_medical_branch.py

UT Medical Branch

---

tx_salaries/utils/transformers/__init__.py
tx_salaries/utils/transformers/ut_md_anderson.py

UT MD Anderson
